# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chase Jensen
email: chasejensen88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
            Hi, I'm Chase. I am a motivated Software Engineer who loves learning and working towards solutions. 
            I'm always trying to improve my own knowledge, skills, and craft, as well as help others along the way. 
            Sometimes the best way to learn is to teach. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://chasejensen.com" # the base hostname & protocol for your site
twitter_username: chasej
github_username:  ruevaughn

# Build settings
markdown: kramdown
